### ISSUE TITLE
Unable to authenticate  confluence

### ISSUE THREAD

**Issue by nagaraju-sunkara** [qwazer/markdown-confluence-gradle-plugin#15]
here is my confluence task

```
confluence {
    authentication 'base64-encoded user:pass'
    restApiUrl 'https://confluence.domain.com/rest/api'
    spaceKey 'ABC'
    sslTrustAll true
    parseTimeout 2000L

    pages {
        page {
            parentTitle  'ABC - Report'
            title "TS - ABC Validation"
            srcFile  file("${buildDir}/reports/report.md")
        }
    }
}
```

I have added required plugins and dependency as mentioned in the page.

Error:

10:41:10 AM: Executing task 'confluence'...

:confluence FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':confluence'.
> <!DOCTYPE html><html><head><title>Apache Tomcat/8.0.47 - Error report</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}.line {height: 1px; background-color: #525D76; border: none;}</style> </head><body><h1>HTTP Status 401 - Basic Authentication Failure - Reason : AUTHENTICATED_FAILED</h1><div class="line"></div><p><b>type</b> Status report</p><p><b>message</b> <u>Basic Authentication Failure - Reason : AUTHENTICATED_FAILED</u></p><p><b>description</b> <u>This request requires HTTP authentication.</u></p><hr class="line"><h3>Apache Tomcat/8.0.47</h3></body></html>

**Comment by qwazer** [comment]
@nagaraju-sunkara check your authentication 
For example, if your user is "admin" password is "admin", auth authentication will be `YWRtaW46YWRtaW4=`
