### ISSUE TITLE
Error in gradle build

### ISSUE THREAD

**Issue by SimonBerry555** [qwazer/markdown-confluence-gradle-plugin#20]
Hi, after setting up my project as per the docs I get this error:

`A problem occurred evaluating root project 'confluenceplugin'.
> Could not find method confluence() for arguments [build_ad5yu0b6fmszmkxjotb5kv29j$_run_closure3@18050b42] on root project 'confluenceplugin' of type org.gradle.api.Project.

Any input on what causes this would be helpful - thanks.

**Comment by qwazer** [comment]
What is the version of gradle you use?

**Comment by SimonBerry555** [comment]
./gradlew --version

------------------------------------------------------------
Gradle 6.3
------------------------------------------------------------

Build time:   2020-03-24 19:52:07 UTC
Revision:     bacd40b727b0130eeac8855ae3f9fd9a0b207c60

Kotlin:       1.3.70
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.6 (Oracle Corporation 11.0.6+8-LTS)
OS:           Mac OS X 10.15.3 x86_64

**Comment by SimonBerry555** [comment]
Hi,

Its version 7.0

Regards

Simon Berry

**Comment by SimonBerry555** [comment]
Any update please?

**Comment by SimonBerry555** [comment]
Fixed the issue, my gradle.build looks like:

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.github.qwazer:markdown-confluence-gradle-plugin:0.9.1'
    }
}

plugins {
    id 'java'
}

apply plugin: 'com.github.qwazer.markdown-confluence'
```
