### ISSUE TITLE
PR for inline images

### ISSUE THREAD

**Issue by SimonBerry555** [qwazer/markdown-confluence-gradle-plugin#22]
Hi - I've raised a PR - could you take a look and get back to me please? Thanks

**Comment by SimonBerry555** [comment]
Hi,

So to release/publish version 0.9.2 so it is accessible I can follow the
steps in how_to_release, I have a few questions if you could answer/confirm
the items in bold please?:

   1. Update version in gradle.properties - *to 0.9.2*
   2. git commit
   3. git tag - *tag is v0.9.2*
   4. git push - *push directly to master? Do I have permission?*
   5. wait for upload in bintray from CI build
   6. go to bintray and publish manually - *do I need a specific account or
   can I just use my own?*
   7. publish to gradle.portal - *please provide details (or link to doc)
   on how to do this.*
   8. update & run test prev_release_availability.gradle- *please provide
   details (or link to doc) on how to do this.*
   9. update README
   <https://github.com/qwazer/markdown-confluence-gradle-plugin/blob/master/README.md>
-
   *what is required in addition to what I have already added?*

Thanks

Simon

**Comment by SimonBerry555** [comment]
Hi,

I have done steps 1-4, the build seems to be broken in travis:

* What went wrong:
332A problem occurred configuring root project
'markdown-confluence-gradle-plugin'.
333> Could not resolve all artifacts for configuration ':classpath'.
334   > Could not download plugin-publish-plugin.jar
(com.gradle.publish:plugin-publish-plugin:0.12.0)
335      > Could not get resource
'https://plugins.gradle.org/m2/com/gradle/publish/plugin-publish-plugin/0.12.0/plugin-publish-plugin-0.12.0.jar'.
336         > Could not GET
'https://plugins.gradle.org/m2/com/gradle/publish/plugin-publish-plugin/0.12.0/plugin-publish-plugin-0.12.0.jar'.
337            > Connection reset




It seems to be having a problem accessing 0.12.0 of the
plugin-publish-plugin even though it is there in
https://plugins.gradle.org/m2/ !

Regards

Simon

**Comment by qwazer** [comment]
HI

> 6. go to bintray and publish manually - *do I need a specific account or
   can I just use my own?*

I will do it under my account on bintray.
 >  7. publish to gradle.portal - *please provide details (or link to doc)
   on how to do this.*

It should be done automatically by build on tag.
Maybe manual approve under my account on gradle.portal will be required

 >  8. update & run test prev_release_availability.gradle- *please provide
   details (or link to doc) on how to do this.*

update version (like in https://github.com/qwazer/markdown-confluence-gradle-plugin/commit/9997d9500352b307181677797e20c6d4a198eb6d) 
uncomment @Ignore on PrevReleaseAvaibilityIT
run tests 
revert changes in PrevReleaseAvaibilityIT (do not commit it)

Note : name of test `prev_release_availability.gradle` is not perfect. This is place to improve

Thanks for your efforts!
Regards

**Comment by qwazer** [comment]
status update:

> 6.go to bintray and publish manually

done, fixed by rebuild 

> 7. publish to gradle.portal

This is pure manual process.
done

**Comment by qwazer** [comment]
issue https://github.com/qwazer/markdown-confluence-gradle-plugin/issues/23 updated to track status
