### ISSUE TITLE
Basic authentication with passwords is deprecated

### ISSUE THREAD

**Issue by ghost** [qwazer/markdown-confluence-gradle-plugin#26]
`> Basic authentication with passwords is deprecated.  For more information, see: https://confluence.atlassian.com/cloud/deprecation-of-basic-authentication-with-passwords-for-jira-and-confluence-apis-972355348.html
`

**Comment by jigga** [comment]
The latest version of the plugin (0.9.3) allows using Confluence Personal Access Tokens (PATs) to authenticate calls to Confluence APIs. Closing the issue now.
