### ISSUE TITLE
wrong build artifact prevent automatic publishing to gradle portal

### ISSUE THREAD

**Issue by qwazer** [qwazer/markdown-confluence-gradle-plugin#42]
The build v0.10.0 adds new build artifact 

```
✅ Build artifacts:
com.github.qwazer.markdown-confluence-gradle-plugin:com.github.qwazer.markdown-confluence.gradle.plugin:v0.10.0
com.github.qwazer.markdown-confluence-gradle-plugin:markdown-confluence-gradle-plugin:v0.10.0
```
see
https://jitpack.io/com/github/qwazer/markdown-confluence-gradle-plugin/v0.10.0/build.log

The previous build has only 1 build artifact:

```
✅ Build artifacts:
com.github.qwazer:markdown-confluence-gradle-plugin:0.9.3
```
see https://jitpack.io/com/github/qwazer/markdown-confluence-gradle-plugin/0.9.3/build.log

Need to fix, otherwise  Gradle team doesn't approve automatic update of new plugin versions:

**Comment by jigga** [comment]
This is already resolved as version 0.10.0 was successfully published to the plugin portal months ago. Closing.
